# Generated by Django 5.0.3 on 2024-03-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ArtistId', models.IntegerField(primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=255)),
                ('ArtistImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('ConcertId', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistId', models.IntegerField()),
                ('ConcertDate', models.DateTimeField()),
                ('Venue', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('TicketQuantity', models.IntegerField()),
                ('TicketPrice', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
