# Generated by Django 5.0.3 on 2024-03-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTickets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('concertId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('paymentType', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
            ],
        ),
    ]
