# Generated by Django 4.2.11 on 2024-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_mytickets_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytickets",
            name="ticketPrice",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mytickets",
            name="ticketSection",
            field=models.IntegerField(default=0),
        ),
    ]
