# Generated by Django 4.2.11 on 2024-04-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="isValid",
            field=models.BooleanField(default=False),
        ),
    ]
